fr:
  languageName: Français
  weight: 1
  contentDir: content/fr
  params:
    description: "CV académique de Hamza Boudhair"

en:
  languageName: English
  weight: 2
  contentDir: content/en
  params:
    description: "Hamza Boudhair Academic CV"
