main:
  - name: Bio
    url: /
    weight: 10

  - name: Education
    url: /#education
    weight: 20

  - name: Experience
    url: /experience/
    weight: 30

  - name: Projects
    url: /projects/
    weight: 40

  - name: Publications
    url: /publications/
    weight: 50

  - name: Certifications
    url: /certifications/
    weight: 60

  - name: Download CV
    url: /uploads/resume.pdf
    weight: 70
